### PR TITLE
Remove duplicate $PATH entries

### PR DESCRIPTION
**Pull request by piranna**
This fixes issue #4.

### CODE REVIEW

**Comment by timoxley** [comment]
Looks good @piranna, could you add a test?

**Comment by piranna** [comment]
Test added :-)

**Comment by timoxley** [comment]
`array-uniq` dependency probably not necessary, especially we're using modern features like `Set` in the test. `Array.from(new Set(items))` will do the same thing.

**Comment by timoxley** [comment]
Also wondering how this effects executable lookup, e.g. if you remove a dupe from right-hand side, it will change the lookup priority, which is no good

**Comment by timoxley** [comment]
the original purpose of shifting the node path on was to ensure lookup for the current `node` acts correctly… perhaps instead of deduping it should check to see if it's appending the same pattern again

**Comment by piranna** [comment]
> array-uniq dependency probably not necessary, especially we're using modern features like Set in the test. Array.from(new Set(items)) will do the same thing.

Didn't know that, I decided to use `array-uniq` because I didn't know what was the minimal compatibility, but if we are already using `Set()` then I can use that instead, that's ok for me. Do you want that I replace `array-uniq` for `Set()`? Are we sure that `Set()` maintains insertion order?

> Also wondering how this effects executable lookup, e.g. if you remove a dupe from right-hand side, it will change the lookup priority, which is no good

We are already changing the lookup priority because we are including the location of the `node` executable. For example, when Node.js is installed on Ubuntu from the oficial PPA the `node` executable is available at `/usr/bin/node` and the PATH is `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`, and because `npmpath` include the location of the Node.js binary, the lookup priority gets changed because `/usr/bin` is added before `/usr/local/sbin` and `/usr/local/bin`. I'm just removing the dupe because it doesn't make sense to have it duplicated if we have already search in that location before...

> the original purpose of shifting the node path on was to ensure lookup for the current node acts correctly… perhaps instead of deduping it should check to see if it's appending the same pattern again

Are you talking about to check previously if we are trying to add a location already available on `$PATH` and if so don't add it? Yeah, it makes sense, but I would add it as an option, not only because it breaks the current behaviour if we set it enabled by default, but also because the current behaviour is the one I'm looking for :-D Imagine someone that currently has some `node_modules/.bin` in its `$PATH`... Do you want that I add it?

In any case, as I told you before removing dupes is a nice to have feature, since it doesn't make sense search on a location twice if we have done it before...

**Comment by piranna** [comment]
Any update on this?

**Comment by piranna** [comment]
I have just rebased the pull-request on top of your changes, could you be able to merge and publish them?

**Comment by timoxley** [comment]
Hi @piranna, sorry about the delay. Can you remove all the whitespace changes and swap `array-uniq` thing for `Set`. It maintains insertion order.

**Comment by piranna** [comment]
> Can you remove all the whitespace changes

The ones between the jsdoc and the functions? I think is clearer that way, but if you don't want them it's ok for me.

> and swap array-uniq thing for Set. It maintains insertion order.

Cool, fine :-)

**Comment by piranna** [comment]
Removed dependency of `array-uniq`.

**Comment by piranna** [comment]
Tests are failling due to lack of support of some ES6 features... Three options here: use `array-uniq`, add some `for` loops (ugly) or the one I think is the better, deprecate support for any version of Node.js before 4.x LTS.

**Comment by piranna** [comment]
Thank you :-)

**Comment by timoxley** [comment]
👍

**Pull request merged**
