### PR TITLE
Add build process; support down to 0.8

### LINKED ISSUE #6: Use of `const` breaks in older nodes
Is there any chance you'd accept a PR either reverting to ES5, or adding a build process to transpile to ES5? This package is in a dependency tree for a package that I want to use in node 0.10 and 0.12 tests.

### PR DESCRIPTION
**Pull request by ljharb**
This ended up being more complex than I hoped, and took me more time to get to :-)

Fixes #6.

If this is accepted, I can make another PR to bring the rest of the code up to modern JS, since babel will handle transpiling it.

### CODE REVIEW

**Comment by timoxley** [comment]
Great stuff

**Comment by ljharb** [comment]
Yay, thanks!

**Comment by ljharb** [comment]
Any chance for a release? This should be a patch or a minor.

**Comment by timoxley** [comment]
@ljharb done 👍 2.0.4

**Pull request merged**
